# Generated by Django 2.2 on 2023-08-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20230807_1024'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
