# Generated by Django 2.2 on 2023-08-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20230807_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
