# Generated by Django 4.2.4 on 2023-08-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='emal',
            new_name='email',
        ),
    ]
