# Generated by Django 4.2.4 on 2023-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_rename_emal_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='personal_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='author',
            name='second_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='twiter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
